version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: >-
    git submodule update --init --recursive

    nuget restore

    choco install nsis -pre
build:
  project: DnmpWindowsClient.sln
  verbosity: normal
after_build:
- cmd: >-
    makensis NSIS/script.nsi

    mkdir output

    cp NSIS/DnmpWindowsClient.Setup.Any.exe output/DnmpWindowsClient.Setup.Any.exe

    7z a output/DnmpWindowsClient.Any.zip ./DnmpWindowsClient/bin/Release/*
artifacts:
- path: output\*
  name: main-binaries
deploy:
- provider: GitHub
  tag: last-appveyor
  release: last-appveyor
  description: Last appveyor build
  auth_token:
    secure: 0VGMXYFZ/k9Ke2OXZ2bVkHWfDX9vx3gCXmCjl4QpkzlGd2LDE6CZwMbunD0tjl+H
  artifact: main-binaries
  draft: true
  force_update: true
  on:
    branch: master